name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: teyik0
          password: dckr_pat_h5eH4ydQ8QNmlkQf1RJh2MgwmPA

      - name: Build Docker Image
        run: |
          docker build -t teyik0/bun-test:latest .

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: teyik0/bun-test:latest
