name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t teyik0/bun-test:latest .

      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: teyik0/bun-test:latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
